spring:
  mail:
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    username: creasylai_public@126.com
    password: ${email.auth_code}
    host: smtp.126.com
