server:
  port: 9002
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
spring:
  cloud:
    gateway:
      routes:
        - id: path_route_user
          uri: lb://lagou-service-user
          predicates:
          - Path=/api/user/**
          filters:
          - StripPrefix=1
        - id: path_route_code
          uri: lb://lagou-service-code
          predicates:
          - Path=/api/code/**
          filters:
          - StripPrefix=1
        - id: path_route_email
          uri: lb://lagou-service-email
          predicates:
          - Path=/api/email/**
          filters:
          - StripPrefix=1